name: CI

on:
#   push:
#     branches: [ main ]
#     paths-ignore:
#       - 'data/**'
#   pull_request:
#     branches: [ main ]
#     paths-ignore:
#       - 'data/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache spacy models
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-spacy-${{ hashFiles('**/requirements.txt') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m spacy download en_core_web_lg

    - name: Run Ruff (lint)
      run: ruff check --output-format=github .
    - name: Run Ruff (format)
      run: ruff format . --check --diff

    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}/src
      run: |
        pytest tests/
